### ISSUE TITLE
Low baudrates not supported error

### ISSUE THREAD

**Issue by consolacion** [lpodkalicki/attiny13-software-uart-library#1]
using an unchanged example from your blog:  https://blog.podkalicki.com/attiny13-reading-temperature-and-humidity-from-dht11/
I get above mentioned error.
No disaster as i have other ways to do it, but I thought I'd mention it

**Comment by WhoseTheNerd** [comment]
Your baudrate is slow, because you are using 8mhz clock instead  of assumed 1.2mhz clock.

**Comment by Boyfinn** [comment]
> using an unchanged example from your blog: https://blog.podkalicki.com/attiny13-reading-temperature-and-humidity-from-dht11/ I get above mentioned error. No disaster as i have other ways to do it, but I thought I'd mention it

Did you uncomment the lines that define `UART_RX_ENABLED `and `UART_RX_ENABLED` in the header?

**Comment by lpodkalicki** [comment]
My intention was to make user decide what features need to be enabled. However, after I read some emails and comments here I see that it is not so intuitive. I will change it. User will have to decided what features need to be disabled.

**Comment by Boyfinn** [comment]
> My intention was to make user decide what features need to be enabled. However, after I read some emails and comments here I see that it is not so intuitive. I will change it. User will have to decided what features need to be disabled.

Yeah, the safeguards just end up giving said error if you disregard the two lines. Though tracing back the error quickly points it out if you've forgotten to uncomment either.
